spring:
  application:
    name: portfolio-grade-personal-finance-tracker
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/personal_finance}
    username: ${DB_USERNAME:finance_user}
    password: ${DB_PASSWORD:finance_password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  mvc:
    problemdetails:
      enabled: true

server:
  error:
    include-message: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  security:
    enabled: true
    username: ${APP_SECURITY_USERNAME:finance-admin}
    password: ${APP_SECURITY_PASSWORD:finance-admin-password}
    role: ${APP_SECURITY_ROLE:API_USER}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    persist-authorization: true
